### ISSUE TITLE
Process has died (Exit code -6)

### ISSUE THREAD

**Issue by yaxsomo** [Slamtec/rplidar_ros#102]
Hello everyone

Im trying to launch the RPLiDAR ROS package to visualize data into Rviz but I cannot resolve this error code

[rplidarNode-2] process has died [pid 5845, exit code -6, cmd /home/yaxsomo/catkin_ws/devel/lib/rplidar_ros/rplidarNode __name:=rplidarNode __log:=/home/yaxsomo/.ros/log/6e07b2aa-9427-11ed-b7ff-d8c0a650f9d1/rplidarNode-2.log].
log file: /home/yaxsomo/.ros/log/6e07b2aa-9427-11ed-b7ff-d8c0a650f9d1/rplidarNode-2*.log

The specified log files are not generated so I cannot find the root cause of this issue.
The device (RPLiDAR A2 M12) is correctly connected to /dev/ttyUSB0 and powered by 5V 2A.
It is working when I launch the ultra_simple script from the SDK GitHub (https://github.com/slamtec/rplidar_sdk)

Could someone help me ?

**Comment by chongin** [comment]
I meet the same exit code, and I solved this problem by this command: sudo chmod 666 /dev/ttyUSB0
