### ISSUE TITLE
Want to run remotely 

### ISSUE THREAD

**Issue by nd013** [Slamtec/rplidar_ros#119]
Hello...
How to connect rplidar remotely through ssh?
When I try to run rplidar_a1.launch through ssh into my raspberry pi terminal 
The terminal was lagged...
& If I do the same thing using an HDMI cable it runs

**Comment by deyouslamtec** [comment]
You should run 'rosrun rplidar_ros rplidarNodeClient' in another terminal, so that you can get the data.
