### ISSUE TITLE
can't setup the rplidar_ros package on ros1 melodic

### ISSUE THREAD

**Issue by tx871217** [Slamtec/rplidar_ros#131]
showing the following warning after ran the `catkin_make`

> /home/ubuntu/armpi_pro/src/rplidar_ros/sdk/src/arch/linux/net_serial.cpp: In member function ‘virtual void rp::arch::net::raw_serial::cancelOperation()’:
> /home/ubuntu/armpi_pro/src/rplidar_ros/sdk/src/arch/linux/net_serial.cpp:428:12: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
>      ::write(_selfpipe[1], "x", 1);
>      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~

then when I run ` roslaunch rplidar_ros rplidar.launch`
it cant find the package

> RLException: [rplidar.launch] is neither a launch file in package [rplidar_ros] nor is [rplidar_ros] a launch file name
> The traceback for the exception was written to the log file

**Comment by deyouslamtec** [comment]
The command for RPLIDAR A1 is :
`roslaunch rplidar_ros view_rplidar_a1.launch`
