### ISSUE TITLE
slamtec rplidar for wheeled robot

### ISSUE THREAD

**Issue by titusece** [Slamtec/rplidar_ros#2]
Hello,
I would like to use rplidar device on wheeled robot, so I need SLAM method here to find my room localization and mapping.
I am able to run the launch files and is it possible to use this launch files for my wheeled robot to perform the move around on my floor, avoiding obstacles etc.,
Can you please help further on this ?

**Comment by tony-slamtec** [comment]
Well, making robot localize and navigate by it self is much more complicated than just a LIDAR node.
For ROS approach, you may need some more knowledge about the movebase node and gmapping node and etc.
But you can also make it easier by buying Slamtec's Slamware solution or its evaluation platform 'SDP Mini', which works out of box and comes with multi platform APIs and tools
