### ISSUE TITLE
ros2 support

### ISSUE THREAD

**Issue by chuan9** [Slamtec/rplidar_ros#22]
hi, developers
May I know if you guys have the play to support ros2/dashing branch or not?
As ros2 is the future of ros, I need support for ros2 now.
Thanks

**Comment by AustinDeric** [comment]
This is a duplicate issue of: https://github.com/Slamtec/rplidar_ros/issues/4

There is a ROS2 port here: https://github.com/allenh1/rplidar_ros/tree/ros2

**Comment by vinicentus** [comment]
This issue should probably be closed...
