### ISSUE TITLE
Working on Noetic using Ubuntu 20.04 ?

### ISSUE THREAD

**Issue by lukelu520** [Slamtec/rplidar_ros#33]
Dear rplidar_ros friends,

We were wondering if anyone run rplidar_ros on Ubuntu 20.04 (w/ ROS Noetic Ninjemys). Is it working as stable as in Melodic using Ubuntu 18.04 or Kinetic using Ubuntu 16.04 ?

Best,
-- Luke

**Comment by AndreV84** [comment]
also if it works with ros2 foxy? on 20.04?

**Comment by adamkrawczyk** [comment]
It works the same way as in melodic, also works with ros2 but I got a little malformed shape

**Comment by AndreV84** [comment]
Thank you for following up!

**Comment by simonbogh** [comment]
Will there be a release to Noetic so it can be installed from binaries?

**Comment by deyouslamtec** [comment]
> Dear rplidar_ros friends,
> 
> We were wondering if anyone run rplidar_ros on Ubuntu 20.04 (w/ ROS Noetic Ninjemys). Is it working as stable as in Melodic using Ubuntu 18.04 or Kinetic using Ubuntu 16.04 ?
> 
> Best, -- Luke

Yes
