### ISSUE TITLE
Will there be a release to Noetic so it can be installed from binaries?

### ISSUE THREAD

**Issue by Timple** [Slamtec/rplidar_ros#40]
Will there be a release to Noetic so it can be installed from binaries?

_Originally posted by @simonbogh in https://github.com/Slamtec/rplidar_ros/issues/33#issuecomment-714505658_

Since installing from apt-get is not the same as the question if the code works.

**Comment by Timple** [comment]
Are there any objections if I do the release?

**Comment by dimaqq** [comment]
poke

**Comment by Timple** [comment]
I see that releases for other distributions also have been done by (it seems) third-party people.
I am not hearing any objections here, so I will go ahead and release for Noetic.

**Comment by Timple** [comment]
https://github.com/ros/rosdistro/pull/31904

**Comment by Timple** [comment]
Available in the testing repositories. Will be available in the next Noetic sync.

Please go ahead and test the binaries!
