### ISSUE TITLE
Compilation Warning in Ubuntu 20.04 / ROS Noetic

### ISSUE THREAD

**Issue by swiz23** [Slamtec/rplidar_ros#43]
When compiling, the following warning pops up...

![Screenshot from 2021-02-15 17-36-36](https://user-images.githubusercontent.com/31753673/108002187-68eb9c80-6fb4-11eb-9bf3-6404fecabe7e.png)

I believe it's getting angry at the two pairs of quote marks at the end of the ROS_INFO line.

**Comment by deyouslamtec** [comment]
thanks. It has been resolved.
