### ISSUE TITLE
Noetic release for Ubuntu Focal

### ISSUE THREAD

**Issue by davefeilseifer** [Slamtec/rplidar_ros#44]
rplidar_ros passes prerelease testing:

generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  noetic default ubuntu focal amd64 \
  --custom-repo \
    rplidar__custom-1:git:https://github.com/Slamtec/rplidar_ros.git:master \
  --level 0 \
  --output-dir ./

ready for release into focal/noetic

**Comment by dimaqq** [comment]
poke!

**Comment by Timple** [comment]
Duplicate of #40 I think :slightly_smiling_face:

**Comment by deyouslamtec** [comment]
Duplicate of #40
