### ISSUE TITLE
Is there a map save and load function?

### ISSUE THREAD

**Issue by hoshianaaa** [Slamtec/rplidar_ros#53]
Is there a map save and load function?

**Comment by gokulmaxi** [comment]
No saving the map  is done using map saver node which is from another package called map_server.
You can run this command to save the map
```bash
$ rosrun map_server map_saver -f "you_filename"
```
If the package is not found,you can install it using the following command(Only for ubuntu based systems)
```bash 
$ sudo apt install ros-$ROS_VERSION-map-server
 ```
