### ISSUE TITLE
Error ,cannot bind to the specified serial port /dev/ttyUSB0 . 

### ISSUE THREAD

**Issue by soumilbaldota** [Slamtec/rplidar_ros#65]
- sudo chmod 666 /dev/ttyUSB0

Above is the suggested fix to add to documentation

**Comment by subham9777** [comment]
try with sudo chmod 777 /dev/ttyUSB0 and also include the serial_port param in your ros launch file as /dev/rplidar

**Comment by tugbakara** [comment]
they are not working

**Comment by deyouslamtec** [comment]
thanks.
