### ISSUE TITLE
为啥S2 的包没有ROS2版本的, 请思岚官方尽早更新.

### ISSUE THREAD

**Issue by alienshengzi** [Slamtec/rplidar_ros#70]
我买了两个激光雷达, A1 和 S2 ,但是S2 没有ros2的包, A1 没有任何反应.
![tu](https://user-images.githubusercontent.com/24715399/145963580-2f9c72b3-167a-4304-854c-a833e1a8a44e.png)

**Comment by CarlDegio** [comment]
#68 
自己改写了一下，适配sdk2.0.0的ros2包，自己在S2之下测试过了，能正常用

**Comment by alienshengzi** [comment]
@CarlDegio 谢啦,大佬,我改一下试试

**Comment by deyouslamtec** [comment]
收到，已更新
