### ISSUE TITLE
RPLIDAR S2 with ROS2 foxy launch file

### ISSUE THREAD

**Issue by debanik123** [Slamtec/rplidar_ros#79]
We have Rplidar S2 but did not find any launch file for rplidar s2 with ros2 foxy.

**Comment by ankbhatia19** [comment]
https://github.com/Slamtec/sllidar_ros2 is possibly what you are looking for

**Comment by deyouslamtec** [comment]
https://github.com/Slamtec/rplidar_ros/tree/ros2，please try the latest version
