### ISSUE TITLE
Ros2-Humble Support missing

### ISSUE THREAD

**Issue by aagrawa3-dev** [Slamtec/rplidar_ros#91]
**Ros2-Humble** is released in May22, I see no news on this repo for its support.
Please comment about plans to support it..

**Comment by lopenguin** [comment]
Here's a repo with a couple of changes that allow the code to be compiled/work with ROS 2 Humble: https://github.com/lopenguin/rplidar_ros2 (see the ros2 branch).

Note that I also made a change to the start/stop motor service, combining the two into one service (toggle_motor). This can be removed by commenting out anything with toggle motor and uncommenting the start/stop motor services. See the commit for details.

**Comment by mrmara** [comment]
On ROS Humble I get the following error:

```
terminate called after throwing an instance of 'rclcpp::exceptions::UninitializedStaticallyTypedParameterException'
  what():  Statically typed parameter 'channel_type' must be initialized.
```

**Comment by deyouslamtec** [comment]
It has been fixed
