### ISSUE TITLE
Make error Ubuntu 22

### ISSUE THREAD

**Issue by msent27** [Slamtec/rplidar_ros#96]
Unable to install on Ubuntu 22.

Make Error at /usr/share/catkin/cmake/catkinConfig.cmake
Could not find package configuration file provided by "roscpp" with any of the following names:
roscppConfig.cmake
roscpp-config.cmake

Thank's in advance for help

**Comment by deyouslamtec** [comment]
sudo apt-get install ros-<distro>-roscpp
